
# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

LTDeliveryBundle:
    resource: "@LTDeliveryBundle/Controller/"
    type:     annotation
    prefix:   /

LTBackendBundle:
    resource: "@LTBackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /backend

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /backend