<?php

namespace LunchTime\DeliveryBundle\Entity\Menu;

use Doctrine\ORM\EntityRepository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getListByItems(array $menuItems)
    {
        $qb = $this->createQueryBuilder('c');
        $ids = array_map(function ($item) { return $item->getId(); }, $menuItems);
        if (empty($ids)) {
            return false;
        }
        $qb->select('c, i')
            ->innerJoin('c.items', 'i')
            ->add('where', $qb->expr()->in('i.id', '?1'))
            ->orderBy('c.title')
            ->addOrderBy('i.title')
            ->setParameter('1', $ids);

        return $qb->getQuery()->getResult();
    }
}