<?php

namespace LunchTime\DeliveryBundle\Entity\Menu;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;


/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    public function getListQuery()
    {
        $qb = $this->createQueryBuilder('i')
            ->select('i');

        return $qb->getQuery();
    }

    public function addContainerQuery($qb)
    {
        /** @var $qb \Doctrine\ORM\QueryBuilder */
        $alias = current($qb->getRootAliases());
        $qb->andWhere($alias.".is_box = true");

        return $qb;
    }

    public function getAvailableBoxes()
    {
        $existing = array_flip(array_map(function ($item) {
            return $item->getBoxType();
        }, $this->findBy(array('is_box' => true))));
        $all = Item::getBoxes();

        return array_diff_key($all, $existing);
    }
}