<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

use LunchTime\DeliveryBundle\Entity\Menu\Item;
/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120830105508 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $menuItem = new Item();
        $isBoxValue = $menuItem->getIsBox() ? "true":"false";
        $boxTypeValue = $menuItem->getBoxType();

        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE menuitem ADD is_box BOOLEAN");
        $this->addSql("ALTER TABLE menuitem ADD box_type VARCHAR(255)");

        $this->addSql("UPDATE menuitem SET is_box = {$isBoxValue}");
        $this->addSql("UPDATE menuitem SET box_type = '{$boxTypeValue}'");

        $this->addSql("ALTER TABLE MenuItem ALTER is_box SET NOT NULL");
        $this->addSql("ALTER TABLE MenuItem ALTER box_type SET NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE MenuItem DROP is_box");
        $this->addSql("ALTER TABLE MenuItem DROP box_type");
    }
}
