<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120730111825 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE menuitem DROP CONSTRAINT FK_93953FBE12469DE2");
        $this->addSql("ALTER TABLE menuitem ADD CONSTRAINT FK_93953FBE12469DE2 FOREIGN KEY (category_id) REFERENCES MenuCategory (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE MenuItem DROP CONSTRAINT fk_93953fbe12469de2");
        $this->addSql("ALTER TABLE MenuItem ADD CONSTRAINT fk_93953fbe12469de2 FOREIGN KEY (category_id) REFERENCES menucategory (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
    }
}
