<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

use LunchTime\DeliveryBundle\Entity\Menu\Item;
/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120830194017 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $boxTypeValue = Item::BOX_MAIN;

        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE menucategory ADD box_type VARCHAR(255)");
        $this->addSql("UPDATE menucategory SET box_type = '{$boxTypeValue}'");
        $this->addSql("ALTER TABLE menucategory ALTER box_type SET NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "postgresql");
        
        $this->addSql("ALTER TABLE MenuCategory DROP box_type");
    }
}
